export const EXPERIENCES = [
  {
    id: 1,
    company: 'Wrocus Technologies',
    logo: '/logos/wrocus.png',
    role: 'Senior Full Stack Developer',
    type: 'Full-time',
    period: 'Jan 2022 – Present',
    duration: '3+ years',
    location: 'India (Remote)',
    current: true,
    description:
      'Leading full stack development of enterprise-grade web platforms across media, recruitment, and streaming domains. Architecting scalable solutions, mentoring junior developers, and driving technical decisions.',
    highlights: [
      'Architected and built a DRM video streaming platform (Shaka Player + Widevine/FairPlay) serving 500K+ MAU',
      'Developed AI-powered recruitment platform reducing time-to-hire by 60% for enterprise clients',
      'Delivered performance optimization projects for News18, Hindustan Times, and Times of India',
      'Built multi-tenant ATS system managing 2000+ active candidates across 5 staffing agencies',
      'Led migration of legacy CRA apps to Next.js App Router achieving Lighthouse scores 90+',
      'Implemented Redis caching strategies reducing API response times by 70%',
    ],
    tech: ['Next.js', 'React.js', 'Node.js', 'MongoDB', 'Redis', 'Shaka Player', 'DRM', 'Docker', 'Tailwind CSS'],
    color: 'from-blue-500 to-purple-500',
  },
  {
    id: 2,
    company: 'TechStack Solutions',
    logo: '/logos/techstack.png',
    role: 'Full Stack Developer',
    type: 'Full-time',
    period: 'Jun 2020 – Dec 2021',
    duration: '1.5 years',
    location: 'India',
    current: false,
    description:
      'Developed full stack web applications for B2B SaaS clients in e-commerce and logistics domains. Contributed to product architecture decisions and implemented real-time features.',
    highlights: [
      'Built a real-time order tracking system using Socket.io for a logistics startup',
      'Developed a multi-vendor e-commerce platform with custom payment gateway integration',
      'Implemented SSO using OAuth 2.0 and JWT authentication for a B2B SaaS product',
      'Optimized MongoDB queries reducing page load times by 50%',
      'Built reusable React component libraries improving team velocity by 30%',
    ],
    tech: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Socket.io', 'Redux', 'Material UI'],
    color: 'from-purple-500 to-cyan-500',
  },
  {
    id: 3,
    company: 'Digital Craftsmen',
    logo: '/logos/digitalcraftsmen.png',
    role: 'Junior MERN Developer',
    type: 'Full-time',
    period: 'Aug 2019 – May 2020',
    duration: '10 months',
    location: 'India',
    current: false,
    description:
      'Started professional career building web applications for small and medium businesses. Gained deep foundational knowledge of the MERN stack and RESTful API design.',
    highlights: [
      'Built 10+ client websites and web applications from scratch',
      'Developed REST APIs for mobile applications serving 10K+ users',
      'Implemented secure user authentication with JWT and bcrypt',
      'Contributed to internal component library used across all client projects',
    ],
    tech: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript', 'CSS3', 'HTML5'],
    color: 'from-cyan-500 to-green-500',
  },
];
