export const SKILL_CATEGORIES = [
  {
    id: 'frontend',
    label: 'Frontend',
    icon: 'Monitor',
    color: 'from-blue-500 to-cyan-500',
    skills: [
      { name: 'React.js', level: 95, years: 5 },
      { name: 'Next.js', level: 92, years: 4 },
      { name: 'JavaScript (ES2024)', level: 95, years: 5 },
      { name: 'Tailwind CSS', level: 90, years: 3 },
      { name: 'Redux / Context API', level: 88, years: 4 },
      { name: 'Framer Motion', level: 82, years: 2 },
      { name: 'Material UI', level: 85, years: 4 },
      { name: 'HTML5 / CSS3', level: 95, years: 5 },
    ],
  },
  {
    id: 'backend',
    label: 'Backend',
    icon: 'Server',
    color: 'from-purple-500 to-pink-500',
    skills: [
      { name: 'Node.js', level: 90, years: 5 },
      { name: 'Express.js', level: 90, years: 5 },
      { name: 'REST API Design', level: 92, years: 5 },
      { name: 'Authentication / JWT', level: 90, years: 4 },
      { name: 'WebSockets / Socket.io', level: 80, years: 3 },
      { name: 'BullMQ / Job Queues', level: 75, years: 2 },
    ],
  },
  {
    id: 'database',
    label: 'Database',
    icon: 'Database',
    color: 'from-green-500 to-emerald-500',
    skills: [
      { name: 'MongoDB', level: 90, years: 5 },
      { name: 'Redis', level: 80, years: 3 },
      { name: 'Mongoose ODM', level: 90, years: 5 },
      { name: 'Database Design', level: 85, years: 4 },
      { name: 'Query Optimization', level: 82, years: 3 },
    ],
  },
  {
    id: 'specialized',
    label: 'Specialized',
    icon: 'Sparkles',
    color: 'from-orange-500 to-red-500',
    skills: [
      { name: 'DRM (Widevine / FairPlay)', level: 85, years: 3 },
      { name: 'Shaka Player', level: 85, years: 3 },
      { name: 'Mux Analytics', level: 80, years: 2 },
      { name: 'Core Web Vitals', level: 90, years: 3 },
      { name: 'SSR / ISR / CSR', level: 92, years: 4 },
      { name: 'AI/LLM API Integration', level: 78, years: 2 },
    ],
  },
  {
    id: 'devops',
    label: 'DevOps & Tools',
    icon: 'Terminal',
    color: 'from-cyan-500 to-blue-500',
    skills: [
      { name: 'Git / GitHub', level: 92, years: 5 },
      { name: 'Docker', level: 72, years: 2 },
      { name: 'Vercel / Netlify', level: 88, years: 4 },
      { name: 'Linux CLI', level: 78, years: 4 },
      { name: 'CI/CD Pipelines', level: 70, years: 2 },
    ],
  },
];

export const TECH_STACK = [
  { name: 'React.js', icon: '/tech/react.svg', category: 'Frontend' },
  { name: 'Next.js', icon: '/tech/nextjs.svg', category: 'Frontend' },
  { name: 'JavaScript', icon: '/tech/javascript.svg', category: 'Frontend' },
  { name: 'Tailwind CSS', icon: '/tech/tailwind.svg', category: 'Frontend' },
  { name: 'Node.js', icon: '/tech/nodejs.svg', category: 'Backend' },
  { name: 'Express.js', icon: '/tech/express.svg', category: 'Backend' },
  { name: 'MongoDB', icon: '/tech/mongodb.svg', category: 'Database' },
  { name: 'Redis', icon: '/tech/redis.svg', category: 'Database' },
  { name: 'Docker', icon: '/tech/docker.svg', category: 'DevOps' },
  { name: 'Git', icon: '/tech/git.svg', category: 'DevOps' },
];
